apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  variant: dev
  org: umich
nameSuffix: -dev
bases:
- ../../base
secretGenerator:
  - name: secrets
    behavior: merge
    type: Opaque
    files:
    - secret/EMAIL_SUBJECT_PREFIX
